symfony/src/Entity/Article.php
<?php

namespace App\Entity;

use App\Enum\ArticleEnum;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\Table(name="articles")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * Cela va service à changer le font awesome sur la page d'accueil
     *
     * @ORM\Column(name="font",type="string", length=255, nullable=true)
     */
    private $font;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstPhone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastPhone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $archived = false;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type = ArticleEnum::BLOG;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToOne(targetEntity="Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    /** @ORM\ManyToMany(targetEntity="Commune", inversedBy="article", cascade={"persist"}) */
    private $communes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Visit", mappedBy="article", orphanRemoval=true)
     */
    private $visits;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="articles", cascade={"persist"})
     */
    private $categories;

    public function __construct()
    {
        $this->communes = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->visits = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getArchived(): ?bool
    {
        return $this->archived;
    }

    public function setArchived(bool $archived): self
    {
        $this->archived = $archived;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(?\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Commune[]
     */
    public function getCommunes(): Collection
    {
        return $this->communes;
    }

    public function addCommune(Commune $commune): self
    {
        if (!$this->communes->contains($commune)) {
            $this->communes[] = $commune;
        }

        return $this;
    }

    public function removeCommune(Commune $commune): self
    {
        if ($this->communes->contains($commune)) {
            $this->communes->removeElement($commune);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Visit[]
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits[] = $visit;
            $visit->setArticle($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->contains($visit)) {
            $this->visits->removeElement($visit);
            // set the owning side to null (unless already changed)
            if ($visit->getArticle() === $this) {
                $visit->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addArticle($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            $category->removeArticle($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFont()
    {
        return $this->font;
    }

    /**
     * @param mixed $font
     */
    public function setFont($font): self
    {
        $this->font = $font;
        return $this;
    }


    /**
     * @return mixed
     */
    public function getFirstPhone()
    {
        return $this->firstPhone;
    }

    /**
     * @param mixed $firstPhone
     */
    public function setFirstPhone($firstPhone): self
    {
        $this->firstPhone = $firstPhone;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastPhone()
    {
        return $this->lastPhone;
    }

    /**
     * @param mixed $lastPhone
     */
    public function setLastPhone($lastPhone): self
    {
        $this->lastPhone = $lastPhone;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

symfony/src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use App\Entity\Commune;
use App\Repository\CommuneRepository;
use Doctrine\ORM\EntityManagerInterface;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', CKEditorType::class, [
                'required' => false
            ])
            ->add('image', ImageType::class, [
                'required' => false
            ]);

        if ($options['show']) {
            $builder->add('font', TextType::class, [
                'required' => false,
                'label' => 'icon',
                'attr' => [
                    'placeholder'=> 'fa-superpowers'
                ],
                'help' => "Voir ceci pour chercher l'icon : https://fontawesome.com/v4.7.0/icons/"
            ]);
        }
    }

    public function onPreSetData(FormEvent $event): void
    {
        $form = $event->getForm();

        $form->add('communes', EntityType::class, [
            'class' => Commune::class,
            'query_builder' => static function (CommuneRepository $repository) {
                return $repository->createQueryBuilder('c')
                    ->innerJoin('c.parent', 'p')
                    ->addOrderBy('p.name', 'ASC')
                    ->addOrderBy('c.name', 'ASC');
            },
            'group_by' => static function (Commune $choice) {
                return $choice->getParent() ? $choice->getParent()->getName() : $choice->getName();
            },
            'mapped' => true,
            'label' => 'Moughataa',
            'multiple' => true,
            'required' => false,
            'attr' => [
                'class' => 'js-select2',
                'style' => "width: 100%",
                'placeholder' => 'Choisir une Mougataa ...',
            ]
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
            'show' => false
        ]);
    }
}

symfony/src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Enum\ArticleEnum;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Controller\BaseController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/article", name="article_")
 */
class ArticleController extends BaseController
{
    /**
     * @Route("/type/blog", name="index_blog", methods={"GET"})
     * @Route("/type/technique", name="index_technique", methods={"GET"})
     */
    public function index(Request $request, ArticleRepository $articleRepository): Response
    {
        if( $request->get('_route') === 'article_index_technique') {
            return $this->render('article/list_technique.html.twig', [
                'articles' => $articleRepository->findBy(['type' => ArticleEnum::TECHNIQUE, 'archived' => false], ['id' => 'DESC'])
            ]);
        }

        return $this->render('article/list_blog.html.twig', [
            'articles' => $articleRepository->findBy(['type' => ArticleEnum::BLOG, 'archived' => false], ['id' => 'DESC'])
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if (!$type = $request->get('type')) {
            throw $this->createNotFoundException('Type l\'article inconnue !');
        }

        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article, ['show' => $type === ArticleEnum::TECHNIQUE]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $article->setType($type);
            $entityManager->persist($article);
            $entityManager->flush();

            $this->flashSuccess('Article créer avec succès !');

            return $this->redirectToRoute('article_index_'.$type);
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
            'type' => $type
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        if (!$type = $request->get('type')) {
            throw $this->createNotFoundException('Type l\'article inconnue !');
        }

        $form = $this->createForm(ArticleType::class, $article, ['show' => $type === ArticleEnum::TECHNIQUE]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setType($type);
            $this->getDoctrine()->getManager()->flush();

            $this->flashSuccess('Article modifié avec succès');

            return $this->redirectToRoute('article_index_'.$type);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
            'type' => $type
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if (!$type = $request->get('type')) {
            throw $this->createNotFoundException('Type de l\'article inconnue !');
        }

        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $article->setArchived(1);
            $entityManager->flush();
            $this->flashSuccess('Article supprimé avec succès !');
        }


        return $this->redirectToRoute('article_index_'.$type);
    }
}

symfony/templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}"
      onsubmit="return confirm('Vous êtes sur de vouloir supprimée ce ' + {{ type }} + ' ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="type" value="{{ type }}">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger btn-sm">Supprimer</button>
</form>

symfony/templates/article/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <section class="panel important">
        {% block _title %}
            <h2>Modifier {{ type|capitalize }}</h2>
        {% endblock %}

        {{ form_start(form) }}
        <div class="twothirds">
            {{ form_row(form.title, {'attr': {'placeholder': 'Nom'}}) }}

            {{ form_row(form.content, {'attr': {'rows': 8, 'cols': 40}}) }}

            {{ form_row(form.image) }}
            {% if article.image %}
                <img src="{{ vich_uploader_asset(article.image, 'imageFile') }}" alt="" width="290" />
            {% endif %}

            {% if 'font' in form|keys %}
                {{ form_label(form.font) }}
                {{ form_widget(form.font) }}
                {{ form_help(form.font) }}
            {% endif %}
        </div>
        <div class="onethird d-flex">
            <div class="mt-auto">
                <input type="submit" value="Soumettre" />
            </div>
        </div>
        <div>
            <a class="btn-cs-danger" href="{{ path('article_index_'~type) }}">Annuler</a>
        </div>
        {{ form_end(form) }}
    </section>

    {% if article.id %}
        <div class="text-right">
            {{ include('article/_delete_form.html.twig') }}
        </div>
    {% endif %}
{% endblock %}

symfony/templates/article/list_blog.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Liste des annonces{% endblock %}

{% block class_body 'admin' %}

{% block body %}
    <section class="panel important">
        <h2>Liste des blogs</h2>

        <div class="text-right">
            <a class="btn-primary btn-sm text-right" href="{{ path('article_new', { type: constant('App\\Enum\\ArticleEnum::BLOG')}) }}">
                <i class="fas fa-plus"></i>
                Nouvelle Blog
            </a>
        </div>

        <table>
            <tr>
                <th>Titre</th>
                <th>Crée</th>
                <th>Actions</th>
                <th>Supprimé</th>
            </tr>
            {% for article in articles %}
                <tr>
                    <td title="{{ article.titleTranslator }}">{{ article.title }}</td>
                    <td>{{ article.createdAt|date('d/m/Y') }}</td>
{#                    <td>#}
{#                        <a href="{{ path('article_show', {'id': article.id}) }}">Afficher</a>#}
{#                    </td>#}
                    <td>
                        <a href="{{ path('article_edit', {'id': article.id, type: constant('App\\Enum\\ArticleEnum::BLOG')}) }}">Modifier</a>
                    </td>
                    <td>
                        <span class="badge badge-secondary">{{ article.archived ? 'oui' : 'non' }}</span>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">Pas d'article disponible...</td>
                </tr>
            {% endfor %}
        </table>
    </section>
{#{% block stylesheets %}#}
{#    {{ parent() }}#}
{#    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">#}
{#{% endblock %}#}
{#{% block javascripts %}#}
{#    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>#}
{#    <script>#}
{#        $(document).ready( function () {#}
{#            $('.js-datatable').DataTable();#}
{#        } );#}
{#    </script>#}
{% endblock %}

symfony/templates/article/list_technique.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Liste des annonces{% endblock %}

{% block class_body 'admin' %}

{% block body %}

    <section class="panel important">
        <h2>Liste des pratiques</h2>

        <div class="text-right">
            <a class="btn-primary btn-sm text-right" href="{{ path('article_new', { type: constant('App\\Enum\\ArticleEnum::TECHNIQUE')}) }}">
                <i class="fas fa-plus"></i>
                Nouvelle pratique
            </a>
        </div>

        <table>
            <tr>
                <th>Nom</th>
                <th>date</th>
                <th>Actions</th>
            </tr>
            {% for article in articles %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.createdAt|date('d/m/Y') }}</td>
{#                    <td>#}
{#                        <a href="{{ path('article_show', {'id': article.id}) }}">Afficher</a>#}
{#                    </td>#}
                    <td>
                        <a href="{{ path('article_edit', {'id': article.id , type: constant('App\\Enum\\ArticleEnum::TECHNIQUE')}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">Pas de pratique disponible...</td>
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}

{#{% block stylesheets %}#}
{#    {{ parent() }}#}
{#    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">#}
{#{% endblock %}#}
{#{% block javascripts %}#}
{#    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>#}
{#    <script>#}
{#        $(document).ready( function () {#}
{#            $('.js-datatable').DataTable();#}
{#        } );#}
{#    </script>#}
{#{% endblock %}#}

symfony/templates/article/new.html.twig
{% extends 'article/edit.html.twig' %}

{% block title %}Nouvelle {{ type|capitalize }}{% endblock %}

{% block _title %}
    <h2>{{ block('title') }}</h2>
{% endblock %}

symfony/templates/article/show.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Update_at</th>
                <td>{{ article.updateAt ? article.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>
                    {% if article.image %}
                        <img src="{{ vich_uploader_asset(article.image, 'imageFile') }}" alt="" height="30" width="30">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ article.content|raw }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ article.slug }}</td>
            </tr>
        </tbody>
    </table>

    <div class="admin-show">
        <div>
            <a class="btn btn-success" href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
        </div>
        <div>
            {{ include('article/_delete_form.html.twig') }}
        </div>
        <div>
            <a class="btn btn-default" href="{{ path('article_index') }}">< back to list</a>
        </div>
    </div>
{% endblock %}